-- 任务故意无外键，避免fanout持锁写任务时隐式获取关系父锁形成锁环；仅内部入口核对永久关系。

CREATE TABLE mk_referral_qualification (
  tenant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户隔离首键',
  relation_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '永久首绑关系ID',
  participant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '固定邀请参与ID',
  goal_type varchar(32) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '可信冻结计划目标；缺计划时为空且不得计数',
  policy_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原关系固定规则摘要，不是主体摘要',
  state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'PENDING待证据、ELIGIBLE有效、INELIGIBLE无效、REVIEW待审',
  reason varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '脱敏资格原因码',
  counted boolean NOT NULL COMMENT '当前是否计入有效人数',
  ever_qualified boolean NOT NULL COMMENT '永久曾达标标记，退款不清除',
  qualification_revision bigint unsigned NOT NULL COMMENT '资格当前投影递增水位',
  evidence_resource_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '权威首单证据资源，供隔离和退款派发追踪',
  evidence_state_version bigint unsigned NOT NULL COMMENT '本次锁定的订单聚合版本，无订单为零',
  member_revision bigint unsigned NOT NULL COMMENT '已知最高C02权威会员修订，仅首次无许可为零，重试不得清除',
  member_evidence_digest char(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '完整C02稳定业务事实独立HMAC，禁止普通低熵摘要',
  registration_anchor_digest char(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '注册事实及首次可信接收时点独立HMAC锚，拒绝重试改宽限，不落注册原值',
  member_quarantined boolean NOT NULL COMMENT '会员同修订冲突或口径漂移永久隔离，无自动清除',
  member_policy varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL COMMENT '绑定时新客权威口径版本',
  first_order_policy varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL COMMENT '可信C03首单口径版本，禁止本地猜测',
  proof_id varchar(128) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '受信许可脱敏证据引用',
  due_seconds bigint NULL COMMENT '观察期精确截止UTC秒，非扫描精度',
  due_nanos int unsigned NULL COMMENT '观察期精确截止纳秒部分',
  task_revision bigint unsigned NOT NULL COMMENT '已处理任务请求水位，不跨订单比较业务版本',
  created_at datetime(6) NOT NULL COMMENT '创建时间UTC微秒',
  updated_at datetime(6) NOT NULL COMMENT '更新时间UTC微秒',
  PRIMARY KEY(tenant_id,relation_id),
  KEY ix_qualification_evidence(tenant_id,evidence_resource_id,relation_id),
  KEY ix_qualification_participant(tenant_id,participant_id,relation_id),
  FOREIGN KEY (tenant_id,relation_id) REFERENCES mk_referral_relation(tenant_id,relation_id),
  FOREIGN KEY (tenant_id,participant_id) REFERENCES mk_referral_participant(tenant_id,participant_id),
  CHECK (state IN ('PENDING','ELIGIBLE','INELIGIBLE','REVIEW')),
  CHECK (goal_type IS NULL OR goal_type IN ('REGISTERED_NEW_CUSTOMER','FIRST_ORDER_SETTLED')),
  CHECK ((member_revision=0 AND member_evidence_digest IS NULL) OR (member_revision>0 AND member_evidence_digest IS NOT NULL AND member_policy IS NOT NULL)),
  CHECK (NOT member_quarantined OR (state='REVIEW' AND NOT counted)),
  CHECK (qualification_revision>0 AND task_revision>0 AND (NOT counted OR (ever_qualified AND goal_type IS NOT NULL AND state='ELIGIBLE'))),
  CHECK ((due_seconds IS NULL AND due_nanos IS NULL) OR (due_seconds IS NOT NULL AND due_nanos IS NOT NULL AND due_nanos<1000000000))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='永久关系资格当前投影及历史首次达标记忆，不是奖励授权';

CREATE TABLE mk_referral_progress (
  tenant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户隔离首键',
  participant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '固定邀请参与ID',
  valid_count bigint unsigned NOT NULL DEFAULT 0 COMMENT '当前有效且已去重关系人数',
  ever_qualified_count bigint unsigned NOT NULL DEFAULT 0 COMMENT '历史首次达标唯一人数，恢复不重复增加',
  progress_revision bigint unsigned NOT NULL DEFAULT 1 COMMENT '仅人数变化时推进的聚合版本',
  created_at datetime(6) NOT NULL COMMENT '创建时间UTC微秒',
  updated_at datetime(6) NOT NULL COMMENT '更新时间UTC微秒',
  PRIMARY KEY(tenant_id,participant_id),
  FOREIGN KEY (tenant_id,participant_id) REFERENCES mk_referral_participant(tenant_id,participant_id),
  CHECK (valid_count<=ever_qualified_count AND progress_revision>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='同参与锁保护的有效及历史唯一人数聚合';

CREATE TABLE mk_referral_evaluation_task (
  tenant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户隔离首键',
  relation_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '永久首绑关系ID',
  participant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '固定邀请参与ID',
  organization_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '由真实永久关系复制的组织，非请求自报',
  shop_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '由真实永久关系复制的店铺，领取时Scope校验',
  requested_revision bigint unsigned NOT NULL COMMENT '每关系独立递增请求水位，每次触发加一',
  processed_revision bigint unsigned NOT NULL DEFAULT 0 COMMENT '最后完成评估的请求水位',
  trigger_resource_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '触发证据提示，不作为选取首单的权威',
  trigger_version bigint unsigned NOT NULL COMMENT '触发订单版本提示，BOUND为零',
  reason varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '最近入队脱敏原因',
  status varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'PENDING待处理、PROCESSING租用、DONE完成',
  available_at datetime(6) NOT NULL COMMENT '候选扫描微秒时间，最终领取按精确秒纳秒复检',
  available_seconds bigint NOT NULL COMMENT '精确可领取UTC秒',
  available_nanos int unsigned NOT NULL COMMENT '精确可领取纳秒部分',
  lease_owner varchar(128) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '内部任务租约标识，不是主体',
  lease_until datetime(6) NULL COMMENT '租约截止UTC微秒，向下取整不延长许可',
  fence bigint unsigned NOT NULL DEFAULT 0 COMMENT '租约及新信号递增栅栏，旧worker不得完成新请求',
  row_version bigint unsigned NOT NULL DEFAULT 1 COMMENT '任务CAS行修订',
  created_at datetime(6) NOT NULL COMMENT '创建时间UTC微秒',
  updated_at datetime(6) NOT NULL COMMENT '更新时间UTC微秒',
  PRIMARY KEY(tenant_id,relation_id),
  KEY ix_evaluation_due(tenant_id,status,available_at,relation_id),
  CHECK (status IN ('PENDING','PROCESSING','DONE')),
  CHECK (requested_revision>0 AND processed_revision<=requested_revision AND available_nanos<1000000000),
  CHECK ((trigger_resource_id IS NULL AND trigger_version=0 AND reason='BOUND') OR (trigger_resource_id IS NOT NULL AND trigger_version>0 AND reason<>'BOUND')),
  CHECK ((status='PROCESSING' AND lease_owner IS NOT NULL AND lease_until IS NOT NULL) OR (status<>'PROCESSING' AND lease_owner IS NULL AND lease_until IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资格可恢复任务及观察期精确调度，显式引用且无父行外键';
