-- 奖励身份不包含规则发布版本/资格修订/重试时间；旧活动升级或跌档重达不得再次建奖。
CREATE TABLE mk_referral_reward (
  tenant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '租户隔离及所有唯一键首列',
  reward_id char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '完整永久业务身份规范编码的SHA256，非原始主体摘要',
  campaign_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原活动ID，跨发布版本固定',
  organization_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原参与组织权限范围',
  shop_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原参与门店权限范围',
  participant_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '邀请人固定参与聚合',
  relation_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '逐人奖励依赖关系，阶梯为空且由非空milestone唯一键裁决',
  beneficiary_key char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '可信规范受益人HMAC索引，非原文或普通低熵摘要',
  subject_key_version bigint unsigned NOT NULL COMMENT '固定主体索引密钥版本，不随请求更换',
  beneficiary_cipher varbinary(2048) NOT NULL COMMENT '复制原参与者或关系的密文，必须按原AAD解密',
  encryption_key_id varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原主体加密密钥引用，不保存明文密钥',
  cipher_source varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '密文原上下文PARTICIPANT或RELATION',
  cipher_resource_id varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原密文所属资源ID，用于可信AAD验证',
  role varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '独立受益角色INVITER或INVITEE',
  mode varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'PER_RELATION逐人或MILESTONE人数阶梯',
  threshold_count bigint unsigned NOT NULL COMMENT '当前有效人数门槛，逐人为一',
  rule_id varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '跨版本稳定奖励规则ID',
  milestone_key varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'relation冒号关系ID或threshold冒号整数，禁止NULL唯一漏洞',
  definition_id varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原固定定义ID',
  definition_version bigint unsigned NOT NULL COMMENT '原固定定义版本',
  generation bigint unsigned NOT NULL COMMENT '原固定发布代次',
  artifact_id varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原固定签名制品引用',
  policy_hash char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '固定规则摘要，不得换成最新发布',
  rule_json json NOT NULL COMMENT '原奖励规则及权益SKU版本引用、个人与活动数量上限',
  quantity int unsigned NOT NULL DEFAULT 1 COMMENT '首期每份奖励一个券单位，双边独立建账',
  source_request_id varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '永久外部请求号，重签重试取消均复用',
  entitlement_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ELIGIBLE' COMMENT '资格ELIGIBLE或永久失效INVALIDATED；技术等待不永久失效',
  authorization_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NONE' COMMENT '授权NONE或CONFIRMED或CANCEL_REQUESTED，与资格分离',
  risk_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PENDING' COMMENT '发前风险PENDING、ALLOW、REJECT、REVIEW、UNAVAILABLE',
  delivery_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NOT_SUBMITTED' COMMENT 'NOT_SUBMITTED、PENDING、UNKNOWN、ACCEPTED、SUCCEEDED、FAILED_FINAL；202非成功',
  compensation_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NONE' COMMENT 'NONE、PENDING、CANCELLED、REVERSED、MANUAL_REVIEW；未知不释放',
  quota_state varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'WAIT_QUOTA' COMMENT 'WAIT_QUOTA、RESERVED、CONSUMED、RELEASED；建账不自动占额',
  qualification_revision bigint unsigned NOT NULL COMMENT '对应资格投影水位，不能代替在线订单证据复核',
  progress_revision bigint unsigned NOT NULL COMMENT '人数聚合水位，阶梯授权还须检查全部依赖证据',
  cancel_revision bigint unsigned NOT NULL DEFAULT 0 COMMENT '首次永久失效栅栏，不因人数恢复清除',
  row_version bigint unsigned NOT NULL DEFAULT 1 COMMENT '奖励状态CAS修订，首次为一',
  created_at datetime(6) NOT NULL COMMENT '首次创建UTC微秒',
  updated_at datetime(6) NOT NULL COMMENT '最后更新UTC微秒',
  PRIMARY KEY(tenant_id,reward_id),
  UNIQUE KEY uq_reward_identity(tenant_id,campaign_id,beneficiary_key,role,rule_id,milestone_key),
  UNIQUE KEY uq_reward_source(tenant_id,source_request_id),
  KEY ix_reward_relation(tenant_id,participant_id,relation_id,entitlement_state,reward_id),
  KEY ix_reward_milestone(tenant_id,participant_id,mode,entitlement_state,threshold_count,reward_id),
  FOREIGN KEY(tenant_id,participant_id) REFERENCES mk_referral_participant(tenant_id,participant_id),
  FOREIGN KEY(tenant_id,relation_id) REFERENCES mk_referral_relation(tenant_id,relation_id),
  CHECK(quantity=1 AND threshold_count>0 AND qualification_revision>0 AND progress_revision>0 AND row_version>0),
  CHECK(role IN ('INVITER','INVITEE')),
  CHECK((mode='PER_RELATION' AND relation_id IS NOT NULL AND threshold_count=1) OR (mode='MILESTONE' AND relation_id IS NULL AND role='INVITER')),
  CHECK(cipher_source IN ('PARTICIPANT','RELATION')),
  CHECK(entitlement_state IN ('ELIGIBLE','INVALIDATED')),
  CHECK((entitlement_state='ELIGIBLE' AND cancel_revision=0) OR (entitlement_state='INVALIDATED' AND cancel_revision>0)),
  CHECK(authorization_state IN ('NONE','CONFIRMED','CANCEL_REQUESTED')),
  CHECK(risk_state IN ('PENDING','ALLOW','REJECT','REVIEW','UNAVAILABLE')),
  CHECK(delivery_state IN ('NOT_SUBMITTED','PENDING','UNKNOWN','ACCEPTED','SUCCEEDED','FAILED_FINAL')),
  CHECK(compensation_state IN ('NONE','PENDING','CANCELLED','REVERSED','MANUAL_REVIEW')),
  CHECK(quota_state IN ('WAIT_QUOTA','RESERVED','CONSUMED','RELEASED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='裂变永久奖励身份与正交状态账本，资格事务建账不代表配额或实际发券';
