{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "marketing.serviceAccountName" . }}
  labels:
    {{- include "marketing.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- if and .Values.flink.enabled .Values.flink.createServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "flink.serviceAccount is required when Flink is enabled" .Values.flink.serviceAccount }}
  labels:
    {{- include "marketing.labels" . | nindent 4 }}
  {{- with .Values.flink.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
