CREATE TABLE mk_referral_award_preparation (
  tenant_id varchar(64) NOT NULL COMMENT '租户隔离键',
  source_system varchar(32) NOT NULL DEFAULT 'marketing-referral' COMMENT '固定裂变来源',
  source_request_id varchar(128) NOT NULL COMMENT '永久来源幂等请求ID',
  reward_id varchar(128) NOT NULL COMMENT '永久奖励身份',
  claims_digest char(71) NOT NULL COMMENT '完整稳定授权声明摘要，不含主体明文',
  payload_hash char(71) NOT NULL COMMENT '首次固定候选载荷摘要',
  qualification_revision bigint NOT NULL COMMENT '首次冻结资格修订号',
  phase varchar(32) NOT NULL COMMENT '准备确认恢复阶段，不表示履约成功',
  state_version bigint NOT NULL COMMENT '每次状态变更递增的CAS行版本',
  lease_owner varchar(256) NOT NULL COMMENT '本地租约所有者',
  lease_fence bigint NOT NULL COMMENT '接管递增栅栏，不得改变远端幂等身份',
  lease_acquired datetime(6) NOT NULL COMMENT '租约开始时间UTC微秒部分',
  lease_acquired_nanos smallint NOT NULL COMMENT '租约开始时间不足微秒的纳秒余数',
  lease_expires datetime(6) NOT NULL COMMENT '租约截止UTC微秒部分，必须结合余数裁决',
  lease_expires_nanos smallint NOT NULL COMMENT '租约截止不足微秒的纳秒余数',
  confirmation_id varchar(256) NULL COMMENT '永久远端确认ID',
  confirmed_at datetime(6) NULL COMMENT '永久确认时间UTC微秒部分',
  confirmed_at_nanos smallint NULL COMMENT '永久确认时间纳秒余数',
  rejection_id varchar(256) NULL COMMENT '明确未确认的权威拒绝证明ID',
  rejected_at datetime(6) NULL COMMENT '权威拒绝时间UTC微秒部分',
  rejected_at_nanos smallint NULL COMMENT '权威拒绝时间纳秒余数',
  accepted_intent_id varchar(256) NULL COMMENT '本地耐久受理意图引用，非履约成功',
  quarantined boolean NOT NULL COMMENT '稳定回执冲突隔离，运行时不得自动解除',
  snapshot_binding char(71) NOT NULL COMMENT '完整Identity规范AAD摘要，仅定位不能代替AEAD认证',
  encryption_key_id varchar(128) NOT NULL COMMENT '受控密钥引用，不保存原密钥',
  candidate_cipher mediumblob NOT NULL COMMENT '固定候选AEAD密文，禁止主体或token明文',
  PRIMARY KEY (tenant_id,source_system,source_request_id),
  UNIQUE KEY uq_referral_preparation_reward (tenant_id,reward_id),
  CONSTRAINT ck_referral_prepare_source CHECK (source_system='marketing-referral'),
  CONSTRAINT ck_referral_prepare_positive CHECK (qualification_revision>0 AND state_version>0 AND lease_fence>0),
  CONSTRAINT ck_referral_prepare_phase CHECK (phase IN ('PREPARED','CONFIRMING','CONFIRM_UNKNOWN','CONFIRMED','ACCEPTED','REJECTED')),
  CONSTRAINT ck_referral_prepare_nanos CHECK (lease_acquired_nanos BETWEEN 0 AND 999 AND lease_expires_nanos BETWEEN 0 AND 999 AND (confirmed_at_nanos IS NULL OR confirmed_at_nanos BETWEEN 0 AND 999) AND (rejected_at_nanos IS NULL OR rejected_at_nanos BETWEEN 0 AND 999)),
  CONSTRAINT ck_referral_prepare_receipt CHECK ((phase IN ('CONFIRMED','ACCEPTED') AND confirmation_id IS NOT NULL AND confirmed_at IS NOT NULL AND confirmed_at_nanos IS NOT NULL) OR (phase NOT IN ('CONFIRMED','ACCEPTED') AND confirmation_id IS NULL AND confirmed_at IS NULL AND confirmed_at_nanos IS NULL)),
  CONSTRAINT ck_referral_prepare_reject CHECK ((phase='REJECTED' AND rejection_id IS NOT NULL AND rejected_at IS NOT NULL AND rejected_at_nanos IS NOT NULL) OR (phase<>'REJECTED' AND rejection_id IS NULL AND rejected_at IS NULL AND rejected_at_nanos IS NULL)),
  CONSTRAINT ck_referral_prepare_accepted CHECK ((phase='ACCEPTED' AND accepted_intent_id IS NOT NULL) OR (phase<>'ACCEPTED' AND accepted_intent_id IS NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin COMMENT='裂变奖励永久准备与确认恢复；无明文主体及令牌，不允许清理抹消在途确认';
