CREATE TABLE mk_referral_award_intake (
  tenant_id varchar(64) NOT NULL COMMENT '租户隔离键',
  source_system varchar(32) NOT NULL DEFAULT 'marketing-referral' COMMENT '固定裂变来源',
  source_request_id varchar(128) NOT NULL COMMENT '永久来源请求ID',
  binding_json mediumtext NOT NULL COMMENT '首次固定非主体Scope与全Identity，不含主体明文',
  binding_digest char(64) NOT NULL COMMENT '固定上下文JSON摘要',
  auth_issued datetime(6) NOT NULL COMMENT '首次候选授权签发UTC微秒部分',
  auth_issued_nanos smallint NOT NULL COMMENT '首次候选授权签发纳秒余数0至999',
  auth_expires datetime(6) NOT NULL COMMENT '首次候选授权截止UTC微秒部分',
  auth_expires_nanos smallint NOT NULL COMMENT '首次候选授权截止纳秒余数0至999',
  risk_action varchar(24) NULL COMMENT '最近可信风险结果，REJECT为永久阻断',
  risk_decision_id varchar(256) NULL COMMENT '风险证明ID',
  risk_issued datetime(6) NULL COMMENT '风险证明签发UTC微秒部分',
  risk_issued_nanos smallint NULL COMMENT '风险证明签发纳秒余数0至999',
  risk_expires datetime(6) NULL COMMENT '风险证明截止UTC微秒部分',
  risk_expires_nanos smallint NULL COMMENT '风险证明截止纳秒余数0至999',
  confirmation_state varchar(32) NULL COMMENT '当前确认状态，与永久receipt独立',
  current_revision bigint NOT NULL DEFAULT 0 COMMENT '最近可信确认账本水位',
  cancel_revision bigint NOT NULL DEFAULT 0 COMMENT '不可逆取消栅栏水位',
  confirmation_id varchar(256) NULL COMMENT '永久确认ID',
  authorization_sequence bigint NOT NULL DEFAULT 0 COMMENT '永久确认序列号',
  confirmed datetime(6) NULL COMMENT '永久确认事实时间UTC微秒部分',
  confirmed_nanos smallint NULL COMMENT '永久确认事实时间纳秒余数0至999',
  rejection_id varchar(256) NULL COMMENT '明确未确认的权威拒绝ID',
  response_issued datetime(6) NULL COMMENT '确认响应证明签发UTC微秒部分',
  response_issued_nanos smallint NULL COMMENT '确认响应证明签发纳秒余数0至999',
  response_expires datetime(6) NULL COMMENT '确认响应证明截止UTC微秒部分',
  response_expires_nanos smallint NULL COMMENT '确认响应证明截止纳秒余数0至999',
  quarantined boolean NOT NULL DEFAULT FALSE COMMENT '同水位或永久receipt冲突隔离',
  accepted_intent_id varchar(64) NULL COMMENT '本地HELD意图引用，不表示发送或履约',
  PRIMARY KEY (tenant_id,source_system,source_request_id),
  FOREIGN KEY (tenant_id,source_system,source_request_id) REFERENCES mk_referral_award_preparation(tenant_id,source_system,source_request_id),
  CHECK (source_system='marketing-referral'),
  CHECK ((auth_issued IS NULL AND auth_issued_nanos IS NULL) OR (auth_issued IS NOT NULL AND auth_issued_nanos IS NOT NULL AND auth_issued_nanos BETWEEN 0 AND 999)),
  CHECK ((auth_expires IS NULL AND auth_expires_nanos IS NULL) OR (auth_expires IS NOT NULL AND auth_expires_nanos IS NOT NULL AND auth_expires_nanos BETWEEN 0 AND 999)),
  CHECK ((risk_issued IS NULL AND risk_issued_nanos IS NULL) OR (risk_issued IS NOT NULL AND risk_issued_nanos IS NOT NULL AND risk_issued_nanos BETWEEN 0 AND 999)),
  CHECK ((risk_expires IS NULL AND risk_expires_nanos IS NULL) OR (risk_expires IS NOT NULL AND risk_expires_nanos IS NOT NULL AND risk_expires_nanos BETWEEN 0 AND 999)),
  CHECK ((confirmed IS NULL AND confirmed_nanos IS NULL) OR (confirmed IS NOT NULL AND confirmed_nanos IS NOT NULL AND confirmed_nanos BETWEEN 0 AND 999)),
  CHECK ((response_issued IS NULL AND response_issued_nanos IS NULL) OR (response_issued IS NOT NULL AND response_issued_nanos IS NOT NULL AND response_issued_nanos BETWEEN 0 AND 999)),
  CHECK ((response_expires IS NULL AND response_expires_nanos IS NULL) OR (response_expires IS NOT NULL AND response_expires_nanos IS NOT NULL AND response_expires_nanos BETWEEN 0 AND 999)),
  CHECK (current_revision>=0 AND cancel_revision>=0 AND cancel_revision<=current_revision),
  CHECK (confirmation_state IS NULL OR confirmation_state IN ('CONFIRMED','CANCEL_REQUESTED','REJECTED')),
  CHECK (risk_action IS NULL OR risk_action IN ('ALLOW','REJECT','REVIEW','CHALLENGE','UNAVAILABLE')),
  CHECK ((confirmation_state IS NULL AND current_revision=0 AND cancel_revision=0 AND confirmation_id IS NULL AND authorization_sequence=0)
    OR (confirmation_state='REJECTED' AND current_revision>0 AND cancel_revision=0 AND confirmation_id IS NULL AND authorization_sequence=0 AND rejection_id IS NOT NULL)
    OR (confirmation_state='CONFIRMED' AND current_revision>0 AND cancel_revision=0 AND confirmation_id IS NOT NULL AND authorization_sequence>0 AND confirmed IS NOT NULL AND confirmed_nanos IS NOT NULL)
    OR (confirmation_state='CANCEL_REQUESTED' AND current_revision>0 AND cancel_revision>0 AND confirmation_id IS NOT NULL AND authorization_sequence>0 AND confirmed IS NOT NULL AND confirmed_nanos IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin COMMENT='裂变固定受理上下文及当前取消栅栏，不保存主体明文';

CREATE TABLE mk_referral_award_held_outbox (
  tenant_id varchar(64) NOT NULL COMMENT '租户隔离键',
  source_system varchar(32) NOT NULL DEFAULT 'marketing-referral' COMMENT '固定裂变来源',
  source_request_id varchar(128) NOT NULL COMMENT '永久来源请求ID',
  intent_id varchar(64) NOT NULL COMMENT '本地HELD意图ID',
  state_name varchar(24) NOT NULL DEFAULT 'HELD' COMMENT 'HELD或CANCEL_HELD，旧relay不得读取',
  created datetime(6) NOT NULL COMMENT '本地创建UTC微秒部分',
  created_nanos smallint NOT NULL COMMENT '本地创建纳秒余数0至999',
  payload_hash char(71) NOT NULL COMMENT '原V10受保护候选载荷摘要；无明文payload',
  PRIMARY KEY (tenant_id,source_system,source_request_id),
  FOREIGN KEY (tenant_id,source_system,source_request_id) REFERENCES mk_referral_award_preparation(tenant_id,source_system,source_request_id),
  CHECK (source_system='marketing-referral'),
  CHECK ((created IS NULL AND created_nanos IS NULL) OR (created IS NOT NULL AND created_nanos IS NOT NULL AND created_nanos BETWEEN 0 AND 999)),
  UNIQUE KEY uq_referral_held_intent (tenant_id,intent_id),
  CHECK (state_name IN ('HELD','CANCEL_HELD'))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin COMMENT='专用裂变HELD发件箱，引用V10密文，未接任何自动投递';

CREATE TABLE mk_referral_award_expected_fact (
  tenant_id varchar(64) NOT NULL COMMENT '租户隔离键',
  source_system varchar(32) NOT NULL DEFAULT 'marketing-referral' COMMENT '固定裂变来源',
  source_request_id varchar(128) NOT NULL COMMENT '永久来源请求ID',
  intent_id varchar(64) NOT NULL COMMENT '本地HELD意图ID',
  state_name varchar(24) NOT NULL DEFAULT 'HELD' COMMENT 'HELD或CANCEL_HELD，旧relay不得读取',
  created datetime(6) NOT NULL COMMENT '本地创建UTC微秒部分',
  created_nanos smallint NOT NULL COMMENT '本地创建纳秒余数0至999',
  reward_id varchar(128) NOT NULL COMMENT '永久奖励ID',
  campaign_id varchar(64) NOT NULL COMMENT '固定活动ID',
  rule_id varchar(128) NOT NULL COMMENT '固定奖励规则ID',
  quantity integer NOT NULL DEFAULT 1 COMMENT '首期预期券数量固定1',
  event_type varchar(64) NOT NULL DEFAULT 'REFERRAL_AWARD_EXPECTED' COMMENT '仅耐久事实，不发布到旧Outbox',
  PRIMARY KEY (tenant_id,source_system,source_request_id),
  FOREIGN KEY (tenant_id,source_system,source_request_id) REFERENCES mk_referral_award_preparation(tenant_id,source_system,source_request_id),
  CHECK (source_system='marketing-referral'),
  CHECK ((created IS NULL AND created_nanos IS NULL) OR (created IS NOT NULL AND created_nanos IS NOT NULL AND created_nanos BETWEEN 0 AND 999)),
  UNIQUE KEY uq_referral_expected_intent (tenant_id,intent_id),
  CHECK (quantity=1 AND state_name IN ('HELD','CANCEL_HELD'))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin COMMENT='专用裂变预期事实，非主体元数据，未接旧publisher';

